import type { Metadata } from "next";
import { Inter, Roboto_Condensed, Host_Grotesk, Passion_One } from "next/font/google";
import "./globals.css";
import Header from "../component/Header";
import Footer from "../component/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
});

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-roboto-condensed",
});

const hostGrotesk = Host_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-host-grotesk",
});

const passionOne = Passion_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-passion-one",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoCondensed.variable} ${hostGrotesk.variable} ${passionOne.variable}`}>
      <body className="antialiased font-inter">
        <Header />
        {children}
        <div className="mt-10" />
        <Footer />
      </body>
    </html>
  );
}
